create table if not exists public.salary_payments (
  id bigint generated by default as identity primary key,
  teacher_id text,
  teacher_name text,
  department text,
  designation text,
  account_number text,
  salary_month text,
  payment_date text,
  payment_method text,
  allowances double precision default 0,
  deductions double precision default 0,
  bonus double precision default 0,
  net_salary double precision default 0,
  final_payable_amount double precision default 0,
  payment_status text default 'Paid',
  transaction_id text,
  generated_by text,
  created_at timestamp with time zone default now()
);

alter table public.salary_payments enable row level security;

create table if not exists public.student_attendance (
  id bigint generated by default as identity primary key,
  admission_no text,
  student_name text,
  class_name text,
  section text,
  attendance_date text,
  status text,
  remarks text,
  created_at timestamp with time zone default now()
);

alter table public.student_attendance enable row level security;

create table if not exists public.teacher_attendance (
  id bigint generated by default as identity primary key,
  teacher_id text,
  teacher_name text,
  attendance_date text,
  status text,
  remarks text,
  created_at timestamp with time zone default now()
);

alter table public.teacher_attendance enable row level security;
